<a href="https://colab.research.google.com/github/Mark12481632/Python-Language/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Different array creation mechanisms

arr1 = np.array([[1,2,3,4],[2,3,4,5],[1,1,3,4]])
arr2 = np.zeros((2,3))
arr3 = np.ones((3,2))

print(arr1)
print(arr2)
print(arr3)

[[1 2 3 4]
 [2 3 4 5]
 [1 1 3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
print(np.arange(0.5, 5.5, 0.5))

np.linspace(start=0.6, stop=6.6, num=50)

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


array([0.6       , 0.72244898, 0.84489796, 0.96734694, 1.08979592,
       1.2122449 , 1.33469388, 1.45714286, 1.57959184, 1.70204082,
       1.8244898 , 1.94693878, 2.06938776, 2.19183673, 2.31428571,
       2.43673469, 2.55918367, 2.68163265, 2.80408163, 2.92653061,
       3.04897959, 3.17142857, 3.29387755, 3.41632653, 3.53877551,
       3.66122449, 3.78367347, 3.90612245, 4.02857143, 4.15102041,
       4.27346939, 4.39591837, 4.51836735, 4.64081633, 4.76326531,
       4.88571429, 5.00816327, 5.13061224, 5.25306122, 5.3755102 ,
       5.49795918, 5.62040816, 5.74285714, 5.86530612, 5.9877551 ,
       6.11020408, 6.23265306, 6.35510204, 6.47755102, 6.6       ])

In [6]:
# Indexing and Slicing.